### ISSUE TITLE
LAGraph tests fail on 32-bit platforms

### ISSUE THREAD

**Issue by mmuetzel** [DrTimothyAldenDavis/SuiteSparse#461]
Some of the ctests of LAGraph fail on 32-bit platforms (Windows or Linux).
E.g.: https://github.com/DrTimothyAldenDavis/SuiteSparse/actions/runs/6616841890/job/17971912574#step:8:5841
```
  95% tests passed, 3 tests failed out of 56
  
  Total Test time (real) = 141.18 sec
  
  The following tests FAILED:
  	  8 - ctest_ConnectedComponents (Failed)
  Errors while running CTest
  	 16 - ctest_Malloc (Failed)
  	 39 - ctest_BF (SEGFAULT)
```

**To Reproduce**
Build LAGraph for a 32-bit platform and run `ctest .` in the build directory.

**Expected behavior**
All tests should pass.

**Desktop (please complete the following information):**
 - OS: observed in the CI with Windows MINGW32, CLANG32 and Alpine Linux x86
 - compiler: `gcc.exe (Rev2, Built by MSYS2 project) 13.2.0` or `clang version 17.0.2 (Target: i686-w64-windows-gnu)` or `gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924`
 - all with OpenBLAS

**Comment by DrTimothyAldenDavis** [comment]
I've fixed the test_Malloc.  I'm unsure about the test_BF and test_ConnectedComponents since those tests look to be passing now.  Is this an intermittent bug?

**Comment by mmuetzel** [comment]
For easier reference: @DrTimothyAldenDavis is likely referring to this change:
https://github.com/DrTimothyAldenDavis/SuiteSparse/commit/e6a5b01877490f043ecd2a3d81bcbe52f1a29f24

**Comment by mmuetzel** [comment]
I rebased #415 to trigger the CI with your changes.

One test still segfaults on MINGW32:
https://github.com/DrTimothyAldenDavis/SuiteSparse/actions/runs/6623534748/job/17990771240?pr=415#step:9:7378
```
  98% tests passed, 1 tests failed out of 56
  
  Total Test time (real) = 146.46 sec
  
  The following tests FAILED:
  	 39 - ctest_BF (SEGFAULT)
  Errors while running CTest
```

The Alpine Linux x86 runner still fails the following tests:
https://github.com/DrTimothyAldenDavis/SuiteSparse/actions/runs/6623534747/job/17990770571#step:8:6136
```
  The following tests FAILED:
  	  8 - ctest_ConnectedComponents (Failed)
  	 39 - ctest_BF (SEGFAULT)
```

I don't know if this is just intermittent.

I'll try to reproduce the crash on MINGW32 locally when I come around to it.

**Comment by DrTimothyAldenDavis** [comment]
> For easier reference: @DrTimothyAldenDavis is likely referring to this change: [e6a5b01](https://github.com/DrTimothyAldenDavis/SuiteSparse/commit/e6a5b01877490f043ecd2a3d81bcbe52f1a29f24)

yes, that's my fix for the malloc / calloc / realloc functions.

**Comment by mmuetzel** [comment]
I can reproduce the segmentation fault in ctest_BF on MINGW32.
That's because the matrix in `west0067.mtx` leads to a negative cycle also in the second round (after converting to absolute values). The test could probably be made more robust to no crash in that case.
The actual reason for that issue seems to be a double precision floating point issue (that apparently only occurs on 32-bit platforms?).
The following change fixes it for me:
``` diff
diff --git a/LAGraph/experimental/algorithm/LAGraph_BF_pure_c_double.c b/LAGraph/experimental/algorithm/LAGraph_BF_pure_c_double.c
index 1c99b5da0..a199cbf18 100644
--- a/LAGraph/experimental/algorithm/LAGraph_BF_pure_c_double.c
+++ b/LAGraph/experimental/algorithm/LAGraph_BF_pure_c_double.c
@@ -44,6 +44,8 @@
     LAGraph_Free ((void**) &pi, NULL) ;     \
 }
 
+#include <float.h>
+
 #include "LG_internal.h"
 #include <LAGraphX.h>
 
@@ -122,7 +124,7 @@ GrB_Info LAGraph_BF_pure_c_double
         {
             i = I[k];
             j = J[k];
-            if (d[j] > d[i] + W[k])
+            if (d[j] > d[i] + W[k] + DBL_EPSILON*d[j])
             {
                 LG_FREE_ALL ;
                 return (GrB_NO_VALUE) ;
```

Does that look reasonable? If it does, I'd be happy to open a PR.

**Comment by mmuetzel** [comment]
I went ahead and opened #469.

**Comment by mmuetzel** [comment]
With that change, the CLANG32 and MINGW32 runners are passing all tests of LAGraph.
But the Arch Linux x86 runner still fails one test:
https://github.com/DrTimothyAldenDavis/SuiteSparse/pull/469/checks#step:8:6129
```
  98% tests passed, 1 tests failed out of 56
  
  Total Test time (real) = 170.27 sec
  
  The following tests FAILED:
  	  8 - ctest_ConnectedComponents (Failed)
```

Not sure, but maybe this is the relevant output of the failing test?
https://github.com/DrTimothyAldenDavis/SuiteSparse/actions/runs/6642440030/job/18047208054?pr=469#step:8:6984
```
  ------ CC_FastSV5:
  # of components: 1
  Component 0, size 6
  LG_check_cc init  time: 3.2e-06 sec
  LG_check_cc component time: 1.27e-05 sec
  LG_check_cc check time: 8  Test interrupted by SIGILL.
```

I don't know how to debug that because I can't reproduce locally...

**Comment by mmuetzel** [comment]
If I understand correctly, the test that would have followed the last entry before the SIGILL in the log is the one for `CC_BORUVKA`. There are a couple of warnings when compiling the sources for that:
https://github.com/DrTimothyAldenDavis/SuiteSparse/actions/runs/6642440030/job/18047208054?pr=469#step:7:4827
```
  [  3%] Building C object src/CMakeFiles/lagraph.dir/algorithm/LG_CC_Boruvka.c.o
  In file included from /home/runner/work/SuiteSparse/SuiteSparse/LAGraph/src/utility/LG_internal.h:29,
                   from /home/runner/work/SuiteSparse/SuiteSparse/LAGraph/src/algorithm/LG_CC_Boruvka.c:28:
  /home/runner/work/SuiteSparse/SuiteSparse/LAGraph/src/algorithm/LG_CC_Boruvka.c: In function 'LG_CC_Boruvka':
  /home/runner/work/SuiteSparse/SuiteSparse/LAGraph/src/algorithm/LG_CC_Boruvka.c:252:59: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    252 |         GRB_TRY (GrB_select (S, NULL, NULL, select_op, S, (uint64_t) Px, NULL));
        |                                                           ^
  /home/runner/work/SuiteSparse/SuiteSparse/LAGraph/include/LAGraph.h:363:28: note: in definition of macro 'GRB_TRY'
    363 |     GrB_Info LG_GrB_Info = GrB_method ;         \
        |                            ^~~~~~~~~~
  /home/runner/work/SuiteSparse/SuiteSparse/LAGraph/src/algorithm/LG_CC_Boruvka.c:252:18: note: in expansion of macro 'GrB_select'
    252 |         GRB_TRY (GrB_select (S, NULL, NULL, select_op, S, (uint64_t) Px, NULL));
        |                  ^~~~~~~~~~
  /home/runner/work/SuiteSparse/SuiteSparse/LAGraph/src/algorithm/LG_CC_Boruvka.c:252:59: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    252 |         GRB_TRY (GrB_select (S, NULL, NULL, select_op, S, (uint64_t) Px, NULL));
        |                                                           ^
  /home/runner/work/SuiteSparse/SuiteSparse/LAGraph/include/LAGraph.h:363:28: note: in definition of macro 'GRB_TRY'
    363 |     GrB_Info LG_GrB_Info = GrB_method ;         \
        |                            ^~~~~~~~~~
  /home/runner/work/SuiteSparse/SuiteSparse/LAGraph/src/algorithm/LG_CC_Boruvka.c:252:18: note: in expansion of macro 'GrB_select'
    252 |         GRB_TRY (GrB_select (S, NULL, NULL, select_op, S, (uint64_t) Px, NULL));
        |                  ^~~~~~~~~~
  /home/runner/work/SuiteSparse/SuiteSparse/LAGraph/src/algorithm/LG_CC_Boruvka.c:252:59: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    252 |         GRB_TRY (GrB_select (S, NULL, NULL, select_op, S, (uint64_t) Px, NULL));
        |                                                           ^
  /home/runner/work/SuiteSparse/SuiteSparse/LAGraph/include/LAGraph.h:363:28: note: in definition of macro 'GRB_TRY'
    363 |     GrB_Info LG_GrB_Info = GrB_method ;         \
        |                            ^~~~~~~~~~
  /home/runner/work/SuiteSparse/SuiteSparse/LAGraph/src/algorithm/LG_CC_Boruvka.c:252:18: note: in expansion of macro 'GrB_select'
    252 |         GRB_TRY (GrB_select (S, NULL, NULL, select_op, S, (uint64_t) Px, NULL));
        |                  ^~~~~~~~~~
```

Maybe that is related...

**Comment by DrTimothyAldenDavis** [comment]
Good catch. I think that's a symptom of the bug. It's not a one line fix but I think I see why the code fails on a 32-bit system. Shouldn't be too hard to fix.  I'll do that as soon as I get back to the keyboard.

**Comment by mmuetzel** [comment]
The warning would probably be silenced by this one-liner:
``` diff
diff --git a/LAGraph/src/algorithm/LG_CC_Boruvka.c b/LAGraph/src/algorithm/LG_CC_Boruvka.c
index 79cc5a3dd..3d443dad9 100644
--- a/LAGraph/src/algorithm/LG_CC_Boruvka.c
+++ b/LAGraph/src/algorithm/LG_CC_Boruvka.c
@@ -249,7 +249,7 @@ int LG_CC_Boruvka
 
         // This step is the costliest part of this algorithm when dealing with
         // large matrices.
-        GRB_TRY (GrB_select (S, NULL, NULL, select_op, S, (uint64_t) Px, NULL));
+        GRB_TRY (GrB_select (S, NULL, NULL, select_op, S, (uintptr_t) Px, NULL));
         GRB_TRY (GrB_Matrix_nvals (&nvals, S)) ;
     }
 
```
I don't know if that would fix the error though...

**Comment by DrTimothyAldenDavis** [comment]
The operator has to change also.

**Comment by DrTimothyAldenDavis** [comment]
I think this change should fix it: https://github.com/DrTimothyAldenDavis/SuiteSparse/commit/9c93865470f6dfcb759afdaed415a24d8c6bc369

Only downside is that `uintprt_t` is an optional type in ANSI C11.  Hopefully all the ANSI C11 compilers implement it anyway.

**Comment by mmuetzel** [comment]
According to cppreference.com, `uintptr_t` is mandatory since C99:
https://en.cppreference.com/w/c/types/integer

Afaict, it is still mandatory for C11 compliant compilers.

Edit: On the other hand, support for `uint64_t` is apparently implementation defined. So, there's no guarantee that the type `uint64_t` exists for all standard compliant implementations. (For the most used platforms, it's probably safe to assume that the type will be defined though.)

**Comment by mmuetzel** [comment]
The CI doesn't trigger automatically for the dev2 branch unfortunately. So, I rebased #415 to trigger it manually.

It looks like the test error on Alpine Linux x86 isn't fixed yet:
```
 98% tests passed, 1 tests failed out of 56
  Errors while running CTest
  
  Total Test time (real) = 204.63 sec
  
  The following tests FAILED:
  	  8 - ctest_ConnectedComponents (Failed)
```
It still seems to receive a SIGILL at the same point:
```
  ------ CC_FastSV5:
  # of components: 1
  Component 0, size 6
  LG_check_cc init  time: 3e-06 sec
  LG_check_cc component time: 4e-07 sec
  LG_check_cc check time: 8e-07 sec
    Test interrupted by SIGILL.
```

The warning when building has disappeared though.
So, the crash is probably caused by something else. It might be somewhere in CC_Boruvka though...

**Comment by mmuetzel** [comment]
From the documentation of GCC:
https://www.gnu.org/software/libc/manual/html_node/Program-Error-Signals.html#index-SIGILL
> *Macro: int `SIGILL`*
> The name of this signal is derived from “illegal instruction”; it usually means your program is trying to execute garbage or a privileged instruction. Since the C compiler generates only valid instructions, `SIGILL` typically indicates that the executable file is corrupted, or that you are trying to execute data. Some common ways of getting into the latter situation are by passing an invalid object where a pointer to a function was expected, or by writing past the end of an automatic array (or similar problems with pointers to automatic variables) and corrupting other data on the stack such as the return address of a stack frame.
>
> `SIGILL` can also be generated when the stack overflows, or when the system has trouble running the handler for a signal.

Maybe, there is still a pointer incorrectly cast to a 64-bit wide type that leads to (parts of) the stack being overwritten...

**Comment by DrTimothyAldenDavis** [comment]
Bummer.  Is the Alpine Linux x86 test done on a 32-bit platform?

The crazy thing is that the Boruvka method is only need when using a GraphBLAS library that is *not* SuiteSparse:

https://github.com/GraphBLAS/LAGraph/blob/7887f54875d5659e701809d623031fe0afd0aa0c/src/algorithm/LAGr_ConnectedComponents.c#L36-L40

Any function with the name LG_* is not user-callable.  I only call LG_CC_Boruvka within the connected components test.  So a short-term solution would be to place all of LG_CC_Boruvka itself inside an `#if !LAGRAPH_SUITESPARSE` test, and also the same in `test_ConnectedComponents`.   I would also tag it with a "fixme" comment that it can result in a SIGILL on the Alpine Linux x86 platform (which compiler is being used for that?).

Then I can try to fix LG_CC_Boruvka later on.

**Comment by DrTimothyAldenDavis** [comment]
LG_CC_Boruvka is also slower that LG_CC_FastSV6, so this is no big loss:

https://github.com/GraphBLAS/LAGraph/blob/7887f54875d5659e701809d623031fe0afd0aa0c/src/algorithm/LAGr_ConnectedComponents.c#L20-L21

**Comment by mmuetzel** [comment]
> Bummer. Is the Alpine Linux x86 test done on a 32-bit platform?

Yes, x86 is a 32-bit platform.

**Comment by DrTimothyAldenDavis** [comment]
Oh, that's right, I guess x86_64 is the 64-bit.  I tend to call both x86 but I guess x86 is purely 32-bit.

**Comment by mmuetzel** [comment]
> the Alpine Linux x86 platform (which compiler is being used for that?)

```
gcc --version
gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924
```

**Comment by mmuetzel** [comment]
What could maybe also matter (if you can't reproduce the crash on your Linux):
Afaict, Alpine Linux is one of the distributions based on musl (instead of glibc).

**Comment by DrTimothyAldenDavis** [comment]
That's an interesting clue.  I have a VirtualBox installed on my Intel MacBook, with a 32-bit debian (glibc based I guess).  I could install Alpine Linux x86 and see if i can replicate the SIGILL so I can track it down.

But in the short term I think simply disabling LG_CC_Boruvka is a decent workaround.  The code would still be there for the "vanilla GraphBLAS" (non-SuiteSparse/GraphBLAS).  They would just have to avoid using it on a 32-bit linux system (at least one with musl, maybe).

**Comment by mmuetzel** [comment]
Disabling that code sounds reasonable to me. If there really is the potential of overwriting the stack (potentially because of a misplaced cast or conversion from an array of pointers to an array of integers), maybe we are just getting "lucky" that this particular test doesn't crash on other platforms...

**Comment by DrTimothyAldenDavis** [comment]
True.  I left it as a FIXME since it does seem fragile to me.  It might even point to a subtle bug inside GraphBLAS itself.  So it's worth tracking down.

This should do the trick: https://github.com/DrTimothyAldenDavis/SuiteSparse/commit/905f0797663b810598cd632d4404c96e384369c8 .

I can trigger the CI workflow manually on the dev2 branch

**Comment by DrTimothyAldenDavis** [comment]
Oh, I guess triggering the "build" workflow doesn't do the Alpine Linux tests?

https://github.com/DrTimothyAldenDavis/SuiteSparse/actions/runs/6655843713

**Comment by mmuetzel** [comment]
The two workflows have separate triggers.

**Comment by DrTimothyAldenDavis** [comment]
Got it.  I see that build.yaml has a "workflow_dispatch:" line but build-arch-emu.yaml doesn't (looking up https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow ).  So can I just added that one line to the top of build-arch-emu.yaml, on the default (dev) branch?

**Comment by mmuetzel** [comment]
IIUC, that would allow maintainers of this repository to manually trigger the workflow.
You'd need to add that line on the branch on which you'd like to trigger the workflow.
If you plan on merging `dev` into `dev2` anyway, adding it on the `dev` branch is probably fine.

**Comment by DrTimothyAldenDavis** [comment]
I'm concerned that this LG_CC_Boruvka method might be fragile on other 32-bit systems.  It could be depending on undefined behavior that happens to work on most 32-bit systems, just failing hard on the one system.  So I will disable it on all 32-bit platforms.  It's not used at all if SuiteSparse/GraphBLAS is used, anyway.

I will reenable it when I track down the bug.

Currently testing this change in the CI for dev2:
https://github.com/DrTimothyAldenDavis/SuiteSparse/commit/167bc1e3ce00aabb3541aa20aeaf71c02034c04f

**Comment by mmuetzel** [comment]
Now it failed one test later (or the one after that?):
```
  ------ CC_BORUVKA:
  
  ------ CC_LACC:
  # of components: 1
  Component   Test interrupted by SIGILL.
```

**Comment by DrTimothyAldenDavis** [comment]
Where is that test failure?  These all seem to pass:
https://github.com/DrTimothyAldenDavis/SuiteSparse/actions/runs/6670295083

**Comment by DrTimothyAldenDavis** [comment]
Oh ... I was confused.  The tests all have a green check mark but the logs show the SIGILL...

**Comment by DrTimothyAldenDavis** [comment]
No luck in my various attempts to fix or even disable LG_CC_Boruvka to avoid the SIGILL.  I'll try installing Alpine Linux x86 on VirtualBox and see if I can replicate the problem there.

**Comment by DrTimothyAldenDavis** [comment]
Well, Alpine Linux isn't installing for me on VirtualBox.  I tried compiling GraphBLAS and LAGraph in Debug mode, and the SIGILL goes away.  So it seems to be affected by -O vs -g.

https://github.com/DrTimothyAldenDavis/SuiteSparse/actions/runs/6679168744/job/18151025972 .

I'll try running the ctest with valgrind; maybe that will find the error.

**Comment by DrTimothyAldenDavis** [comment]
Oh ... it's an error inside memcpy, of all places, and only shows up with "-g -O -O3", not "-g".  It's not in LG_CC_Boruvka, but in LG_CC_FastSV6.c inside this loop:

https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/0cfb8c40c228e947e90aca0b12566608f91bb575/LAGraph/src/algorithm/LG_CC_FastSV6.c#L603-L611

I think I might know why: memcpy is not guaranteed to work if the source and destination overlap.  I didn't write this code, but it's possible the source/destination are overlapped.  I'll just rewrite that memcpy as a simple for loop.

**Comment by mmuetzel** [comment]
That does make sense. If that test somehow ~~overwrites the stack~~ corrupts memory, some subsequent test might fail.

> I didn't write this code, but it's possible the source/destination are overlapped. I'll just rewrite that memcpy as a simple for loop.

Iiuc, `memcpy` is fast. But it might handle overlapping memory incorrectly. `memmove` might be slower, but it handles overlapping memory.
While it is slower than `memcpy`, it might still be implemented more efficient than a simple `for` loop.

**Comment by mmuetzel** [comment]
It's interesting that this wasn't a 32-bit issue after all. But nice to see that the CI coverage is wide enough to catch such an issue. 👍

Afaict, there are static code analyzers (CodeQL) that integrate nicely with GitHub. They are meant to produce as little noise as possible. But maybe they would have caught this or similar issues.
I can try to check if that could be reasonably run for SuiteSparse when I come around to it.

**Comment by DrTimothyAldenDavis** [comment]
Thanks -- I was considering memmove but wasn't sure if it would be available in all of the standard libraries.  Yes, memmove would be faser.

memmove_s isn't necessary, though.   The method won't copy past the end of any array, nor will it have any null pointers.

**Comment by DrTimothyAldenDavis** [comment]
I had to run the tests with valgrind in order to find it.  I then disabled it after finding the bug because valgrind doesn't appear on Windows.

See for example the "sudo apt install valgrind", and the like, in the workflows, and the commented out "add_test" lines in the LAGraph cmake scripts.

**Comment by mmuetzel** [comment]
Thanks for your persistence in tracking this down.

Closing as fixed. 👍
